### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bulltorious** [openannotation/annotator-store#130]
Good evening,

This isn't really an issue per say, but I am hoping for help installing it.  I am using the latest Fedora Core.

When I run the last step "python run.py" I get the following error:

>(pyenv)[root@csSrv-FedoraCore01 annotator-store-master]# python run.py
2015-12-02 19:53:32 4462 annotator.elasticsearch [INFO] Creating index 'annotator'.
2015-12-02 19:53:34 4462 elasticsearch [WARNING] PUT /annotator/_mapping/annotation [status:400 request:0.200s]
Traceback (most recent call last):
  File "run.py", line 114, in <module>
    main(sys.argv)
  File "run.py", line 67, in main
    annotation.Annotation.create_all()
  File "/home/mellis/Documents/annotator-store-master/annotator/elasticsearch.py", line 105, in create_all
    body=mapping)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 289, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception')
(pyenv)[root@csSrv-FedoraCore01 annotator-store-master]# python run.py
2015-12-02 19:53:32 4462 annotator.elasticsearch [INFO] Creating index 'annotator'.
2015-12-02 19:53:34 4462 elasticsearch [WARNING] PUT /annotator/_mapping/annotation [status:400 request:0.200s]
Traceback (most recent call last):
  File "run.py", line 114, in <module>
    main(sys.argv)
  File "run.py", line 67, in main
    annotation.Annotation.create_all()
  File "/home/mellis/Documents/annotator-store-master/annotator/elasticsearch.py", line 105, in create_all
    body=mapping)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 289, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception')
(pyenv)[root@csSrv-FedoraCore01 annotator-store-master]# python run.py
2015-12-02 19:53:32 4462 annotator.elasticsearch [INFO] Creating index 'annotator'.
2015-12-02 19:53:34 4462 elasticsearch [WARNING] PUT /annotator/_mapping/annotation [status:400 request:0.200s]
Traceback (most recent call last):
  File "run.py", line 114, in <module>
    main(sys.argv)
  File "run.py", line 67, in main
    annotation.Annotation.create_all()
  File "/home/mellis/Documents/annotator-store-master/annotator/elasticsearch.py", line 105, in create_all
    body=mapping)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 289, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception')
(pyenv)[root@csSrv-FedoraCore01 annotator-store-master]# python run.py
2015-12-02 19:53:32 4462 annotator.elasticsearch [INFO] Creating index 'annotator'.
2015-12-02 19:53:34 4462 elasticsearch [WARNING] PUT /annotator/_mapping/annotation [status:400 request:0.200s]
Traceback (most recent call last):
  File "run.py", line 114, in <module>
    main(sys.argv)
  File "run.py", line 67, in main
    annotation.Annotation.create_all()
  File "/home/mellis/Documents/annotator-store-master/annotator/elasticsearch.py", line 105, in create_all
    body=mapping)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 289, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception')
(pyenv)[root@csSrv-FedoraCore01 annotator-store-master]# python run.py
2015-12-02 19:53:32 4462 annotator.elasticsearch [INFO] Creating index 'annotator'.
2015-12-02 19:53:34 4462 elasticsearch [WARNING] PUT /annotator/_mapping/annotation [status:400 request:0.200s]
Traceback (most recent call last):
  File "run.py", line 114, in <module>
    main(sys.argv)
  File "run.py", line 67, in main
    annotation.Annotation.create_all()
  File "/home/mellis/Documents/annotator-store-master/annotator/elasticsearch.py", line 105, in create_all
    body=mapping)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 289, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception')
(pyenv)[root@csSrv-FedoraCore01 annotator-store-master]# python run.py
2015-12-02 19:53:32 4462 annotator.elasticsearch [INFO] Creating index 'annotator'.
2015-12-02 19:53:34 4462 elasticsearch [WARNING] PUT /annotator/_mapping/annotation [status:400 request:0.200s]
Traceback (most recent call last):
  File "run.py", line 114, in <module>
    main(sys.argv)
  File "run.py", line 67, in main
    annotation.Annotation.create_all()
  File "/home/mellis/Documents/annotator-store-master/annotator/elasticsearch.py", line 105, in create_all
    body=mapping)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 289, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception')
(pyenv)[root@csSrv-FedoraCore01 annotator-store-master]# python run.py
2015-12-02 19:53:32 4462 annotator.elasticsearch [INFO] Creating index 'annotator'.
2015-12-02 19:53:34 4462 elasticsearch [WARNING] PUT /annotator/_mapping/annotation [status:400 request:0.200s]
Traceback (most recent call last):
  File "run.py", line 114, in <module>
    main(sys.argv)
  File "run.py", line 67, in main
    annotation.Annotation.create_all()
  File "/home/mellis/Documents/annotator-store-master/annotator/elasticsearch.py", line 105, in create_all
    body=mapping)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 289, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception')
(pyenv)[root@csSrv-FedoraCore01 annotator-store-master]# python run.py
2015-12-02 19:53:32 4462 annotator.elasticsearch [INFO] Creating index 'annotator'.
2015-12-02 19:53:34 4462 elasticsearch [WARNING] PUT /annotator/_mapping/annotation [status:400 request:0.200s]
Traceback (most recent call last):
  File "run.py", line 114, in <module>
    main(sys.argv)
  File "run.py", line 67, in main
    annotation.Annotation.create_all()
  File "/home/mellis/Documents/annotator-store-master/annotator/elasticsearch.py", line 105, in create_all
    body=mapping)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 289, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception')
(pyenv)[root@csSrv-FedoraCore01 annotator-store-master]# python run.py
2015-12-02 19:53:32 4462 annotator.elasticsearch [INFO] Creating index 'annotator'.
2015-12-02 19:53:34 4462 elasticsearch [WARNING] PUT /annotator/_mapping/annotation [status:400 request:0.200s]
Traceback (most recent call last):
  File "run.py", line 114, in <module>
    main(sys.argv)
  File "run.py", line 67, in main
    annotation.Annotation.create_all()
  File "/home/mellis/Documents/annotator-store-master/annotator/elasticsearch.py", line 105, in create_all
    body=mapping)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 289, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception')
(pyenv)[root@csSrv-FedoraCore01 annotator-store-master]# python run.py
2015-12-02 19:53:32 4462 annotator.elasticsearch [INFO] Creating index 'annotator'.
2015-12-02 19:53:34 4462 elasticsearch [WARNING] PUT /annotator/_mapping/annotation [status:400 request:0.200s]
Traceback (most recent call last):
  File "run.py", line 114, in <module>
    main(sys.argv)
  File "run.py", line 67, in main
    annotation.Annotation.create_all()
  File "/home/mellis/Documents/annotator-store-master/annotator/elasticsearch.py", line 105, in create_all
    body=mapping)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 289, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/mellis/Documents/annotator-store-master/pyenv/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception')'
>

Then elasticsearch spits the following error:
>[2015-12-02 19:53:33,333][INFO ][cluster.metadata         ] [Madelyne Pryor] [annotator] creating index, cause [api], templates [], shards [5]/[1], mappings []
[2015-12-02 19:53:34,089][DEBUG][action.admin.indices.mapping.put] [Madelyne Pryor] failed to put mappings on indices [[annotator]], type [annotation]
MapperParsingException[Mapping definition for [tags] has unsupported parameters:  [index_name : tag]]
	at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:266)
	at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:260)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:312)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:223)
	at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:139)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:210)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:191)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:387)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$2.execute(MetaDataMappingService.java:386)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:388)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-12-02 19:53:34,093][INFO ][rest.suppressed          ] /annotator/_mapping/annotation Params: {index=annotator, type=annotation}
MapperParsingException[Mapping definition for [tags] has unsupported parameters:  [index_name : tag]]
	at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:266)
	at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:260)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseProperties(ObjectMapper.java:312)
	at org.elasticsearch.index.mapper.object.ObjectMapper$TypeParser.parseObjectOrDocumentTypeProperties(ObjectMapper.java:223)
	at org.elasticsearch.index.mapper.object.RootObjectMapper$TypeParser.parse(RootObjectMapper.java:139)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:210)
	at org.elasticsearch.index.mapper.DocumentMapperParser.parseCompressed(DocumentMapperParser.java:191)
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:387)
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$2.execute(MetaDataMappingService.java:386)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:388)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
>

I know that is alot of text, but any idea where else I can ask for questions?  I am using the latest version of everything.

**Comment by Treora** [comment]
Hi, I am not active in this project anymore, but after a quick look I guess the problem may be that your elasticsearch is too new. If I'm not mistaken, the core error in the long log seems to be:
> MapperParsingException[Mapping definition for [tags] has unsupported parameters: [index_name : tag]]

Apparently in elasticsearch 2 they removed the `index_name` parameter (see their [breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_literal_index_name_literal_and_literal_path_literal_removed)).
I would try it with elasticsearch 1.x, and if that works the annotator-store readme should be updated. (and at some moment perhaps the code should be upgraded to work with ES2)

Please let know (and close issue) if it works. :)

**Comment by bulltorious** [comment]
That seemed to fix it.  Thanks !

**Comment by tilgovi** [comment]
Thanks, @Treora!

**Comment by tilgovi** [comment]
Closed this and opened #133.
