### ISSUE TITLE
Elasticsearch 2 compatibility

### ISSUE THREAD

**Issue by tilgovi** [openannotation/annotator-store#133]

**Comment by nobita-isc** [comment]
Is annotator stored fully compatible with Elasticssearch 2? I've just installed Elasticsearch 2.2 and got the following errors:

(pyenv) root@d05c140e6f77:/home/annotator-store# python run.py
2016-03-03 16:32:13 1862 annotator.elasticsearch [INFO] Creating index 'annotator'.
2016-03-03 16:32:13 1862 elasticsearch [WARNING] PUT /annotator/_mapping/annotation [status:400 request:0.110s]
Traceback (most recent call last):
  File "run.py", line 114, in <module>
    main(sys.argv)
  File "run.py", line 67, in main
    annotation.Annotation.create_all()
  File "/home/annotator-store/annotator/elasticsearch.py", line 96, in create_all
    body=mapping)
  File "/home/annotator-store/pyenv/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(_args, params=params, *_kwargs)
  File "/home/annotator-store/pyenv/local/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 289, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/home/annotator-store/pyenv/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/home/annotator-store/pyenv/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/annotator-store/pyenv/local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
**elasticsearch.exceptions.RequestError: TransportError(400, u'mapper_parsing_exception')**

**Comment by arthur24b6** [comment]
See: https://github.com/ackermann/annotator-store/commit/a606436874a419186994df2150b52f05d5b45a54

**Comment by nobita-isc** [comment]
Thanks a lot.
